version: '3'
services:
  
  mysql:
    image: mysql/mysql-server:latest
    container_name: c_mysql
    ports:
      - 3306:3306

    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    networks:
      webnet:

  web:
    image: davidrobl/swapit
    container_name: c_web6
    links:
       - mysql
    depends_on:
      - mysql
    ports:
      - 8443:8443
    restart: on-failure
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    networks:
      webnet:
  

     
networks:
  webnet: